
SET IDENTITY_INSERT [dbo].[category] ON

INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (1, 1, N'Thời Trang Nữ', NULL, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (2, 1, N'Thời Trang Nam', NULL, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (5, 1, N'Phụ Kiện Thời Trang', NULL, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (6, 1, N'Thiết Bị Điện Gia Dụng', NULL, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (8, 1, N'Điện Thoại & Phụ Kiện', NULL, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (11, 1, N'Giày Dép Nữ', NULL, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (13, 1, N'Đồng Hồ', NULL, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (14, 2, N'Quần', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (15, 2, N'Áo', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (16, 2, N'Quần đùi', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (17, 2, N'Váy', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (18, 2, N'Quẩn jeans', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (19, 2, N'Đầm', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (20, 2, N'Váy cưới', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (21, 2, N'Đồ liền thân', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (22, 2, N'Áo khoác', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (23, 2, N'Hoodie và Áo nỉ', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (24, 2, N'Bộ', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (25, 2, N'Đồ lót', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (26, 2, N'Đồ ngủ', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (27, 2, N'Đồ bầu', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (28, 2, N'Đồ truyền thống', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (29, 2, N'Đồ hóa trang', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (30, 2, N'Khác', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (31, 2, N'Vớ/Tất', 1, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (32, 2, N'Quần jeans', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (33, 2, N'Hoodie & Áo nỉ', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (34, 2, N'Áo len', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (35, 2, N'Áo khoác', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (36, 2, N'Com lê', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (37, 2, N'Quần dài', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (38, 2, N'Quần đùi', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (39, 2, N'Áo', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (40, 2, N'Áo lót', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (41, 2, N'Đồ ngủ', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (42, 2, N'Bộ', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (43, 2, N'Trang phụ truyền thống', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (44, 2, N'Trang phục ngành nghề', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (45, 2, N'Tất/Vớ', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (46, 2, N'Khác', 2, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (47, 2, N'Lắc chân', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (48, 2, N'Mũ', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (49, 2, N'Dây chuyền', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (50, 2, N'Kính mắt', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (51, 2, N'Thắt lưng', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (52, 2, N'Cà vạt & Nơ cổ', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (53, 2, N'Bộ phụ kiện', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (54, 2, N'Phụ kiện thêm', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (55, 2, N'Khác', 5, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (56, 2, N'Máy chiếu & Phụ kiện', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (57, 2, N'Thiết bị điện gia dụng nhỏ', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (58, 2, N'Thiết bị điện gia dụng lớn', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (59, 2, N'Tivi & Phụ kiện', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (60, 2, N'Đồ gia dụng nhà bếp', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (61, 2, N'Mạch điện & Phụ tùng', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (62, 2, N'Pin', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (63, 2, N'Thiết bị điều khiển từ xa', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (64, 2, N'Khác', 6, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (65, 2, N'Thẻ sim', 8, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (66, 2, N'Máy tính bảng', 8, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (67, 2, N'Điện thoại', 8, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (68, 2, N'Thiết bị đeo thông minh

', 8, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (69, 2, N'Phụ kiện', 8, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (70, 2, N'Bộ đàm', 8, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (71, 2, N'Khác', 8, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (72, 2, N'Bốt', 11, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (73, 2, N'Giày thể thao/ sneaker', 11, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (74, 2, N'Giày đế bằng', 11, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (75, 2, N'Giày cao gót', 11, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (76, 2, N'Giày đế xuồng', 11, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (77, 2, N'Xăng-đan và dép', 11, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (78, 2, N'Phụ kiện & chăm sóc giày', 11, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (79, 2, N'Khác', 11, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (80, 2, N'Đồng hồ nữ', 13, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (81, 2, N'Đồng hồ nam', 13, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (82, 2, N'Bộ đồng hồ & Đồng hồ cặp', 13, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (83, 2, N'Phụ kiện đồng hồ', 13, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (84, 2, N'Khác', 13, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (85, 3, N'Áo hai dây và ba lỗ', 15, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (86, 3, N'Áo ống', 15, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (87, 3, N'Áo thun', 15, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (88, 3, N'Áo sơ mi', 15, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (89, 3, N'Áo polo', 15, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (90, 3, N'Áo liền thân', 15, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (91, 3, N'Khác', 15, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (92, 3, N'Quần legging', 14, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (93, 3, N'Quần dài', 14, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (94, 3, N'Khác', 14, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (95, 3, N'Quần đùi', 16, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (96, 3, N'Quần váy', 16, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (97, 3, N'Khác', 16, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (98, 3, N'Đồ bay (Jumpsuits)', 21, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (99, 3, N'Đồ bay ngắn (playsuits)', 21, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (100, 3, N'Quần yếm', 21, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (101, 3, N'Khác', 21, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (102, 3, N'Áo khoác mùa đông', 22, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (103, 3, N'Áo choàng', 22, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (104, 3, N'Áo blazer', 22, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (105, 3, N'Áo khoác ngoài', 22, NULL)
GO
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (106, 3, N'Áo vest', 22, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (107, 3, N'Khác', 22, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (108, 3, N'Áo khoác nỉ', 23, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (109, 3, N'Áo hoodies', 23, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (110, 3, N'Khác', 23, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (111, 3, N'Bộ đồ đôi', 24, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (112, 3, N'Bộ đồ gia đình', 24, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (113, 3, N'Đồ lẻ', 24, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (114, 3, N'Khác', 24, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (115, 3, N'Bộ đồ lót', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (116, 3, N'Áo ngực', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (117, 3, N'Quần lót', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (118, 3, N'Đồ lót giữ nhiệt', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (119, 3, N'Phụ kiện đồ lót', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (120, 3, N'Đồ định hình', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (121, 3, N'Đồ lót bảo hộ', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (122, 3, N'Đồ lót gợi cảm', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (123, 3, N'Khác', 25, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (124, 3, N'Pyjama', 26, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (125, 3, N'Váy ngủ', 26, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (126, 3, N'Áo choàng ngủ, Áo khoác kimono', 26, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (127, 3, N'Khác', 26, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (128, 3, N'Áo ngực cho con bú', 27, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (129, 3, N'Đầm bầu', 27, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (130, 3, N'Áo bầu', 27, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (131, 3, N'Đồ mặc cho con bú', 27, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (132, 3, N'Bộ đồ bầu', 27, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (133, 3, N'Quần bầu, Váy bầu', 27, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (134, 3, N'Khác', 27, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (135, 3, N'Áo', 28, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (136, 3, N'Quần và chân váy', 28, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (137, 3, N'Bộ', 28, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (138, 3, N'Đầm', 28, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (139, 3, N'Khác', 28, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (140, 3, N'Tất', 31, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (141, 3, N'Quần tất', 31, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (142, 3, N'Khác', 31, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (143, 3, N'Áo hoodie', 33, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (144, 3, N'Áo nỉ', 33, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (145, 3, N'Khác', 33, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (146, 3, N'Áo khoác mùa đông & Áo choàng', 35, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (147, 3, N'Áo khoác', 35, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (148, 3, N'Áo khoác vest', 35, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (149, 3, N'Khác', 35, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (150, 3, N'Bộ Com lê', 36, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (151, 3, N'Áo Khoác & Blazer', 36, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (152, 3, N'Quần âu', 36, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (153, 3, N'Áo vest & Gi lê', 36, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (154, 3, N'Khác', 36, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (155, 3, N'Quần túi hộp', 37, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (156, 3, N'Quần jogger', 37, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (157, 3, N'Quần dài', 37, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (158, 3, N'Khác', 37, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (159, 3, N'Áo sơ mi', 39, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (160, 3, N'Áo polo', 39, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (161, 3, N'Áo thun', 39, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (162, 3, N'Áo ba lỗ', 39, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (163, 3, N'Khác', 39, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (164, 3, N'Quần lót', 40, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (165, 3, N'Áo lót', 40, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (166, 3, N'Đồ lót giữ nhiệt', 40, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (167, 3, N'Khác', 40, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (168, 3, N'Áo', 43, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (169, 3, N'Quần', 43, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (170, 3, N'Bộ', 43, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (171, 3, N'Khác', 43, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (172, 3, N'Kính mát', 50, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (173, 3, N'Gọng kính', 50, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (174, 3, N'Hộp kính và phụ kiện', 50, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (175, 3, N'Khác', 50, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (176, 3, N'Trâm & Ghim cài áo', 54, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (177, 3, N'Miếng vá áo', 54, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (178, 3, N'Mặt dây chuyền và Charm', 54, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (179, 3, N'Măng sét nam', 54, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (180, 3, N'Hình xăm dán', 54, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (181, 3, N'Khẩu trang thời trang', 54, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (182, 3, N'Khăn tay', 54, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (183, 3, N'Khác', 54, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (184, 3, N'Máy chiếu & Màn hình chiếu', 56, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (185, 3, N'Bút trình chiếu', 56, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (186, 3, N'Khác', 56, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (187, 3, N'Thiết bị vệ sinh chân & Thư giãn', 57, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (188, 3, N'Máy tăm nước', 57, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (189, 3, N'Máy may & Phụ kiện', 57, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (190, 3, N'Điện thoại', 57, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (191, 3, N'Bàn là khô & Hơi nước', 57, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (192, 3, N'Thiết bị xử lý không khí', 57, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (193, 3, N'Máy hút bụi & Thiết bị làm sạch sàn', 57, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (194, 3, N'Khác', 57, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (195, 3, N'Máy giặt & Máy sấy', 58, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (196, 3, N'Máy nước nóng', 58, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (197, 3, N'Thiết bị làm mát', 58, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (198, 3, N'Thiết bị sấy khô nệm & Giày', 58, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (199, 3, N'Máy sưởi', 58, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (200, 3, N'Khác', 58, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (201, 3, N'Tivi', 59, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (202, 3, N'Ăng ten Tivi', 59, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (203, 3, N'Tivi box & Đầu thu kỹ thuật số', 59, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (204, 3, N'Giá treo tivi', 59, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (205, 3, N'Khác', 59, NULL)
GO
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (206, 3, N'Máy lọc nước', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (207, 3, N'Ấm đun siêu tốc', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (208, 3, N'Tủ ủ rượu', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (209, 3, N'Máy ép, Xay sinh tố & Máy làm sữa đậu nành', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (210, 3, N'Máy pha cà phê & Phụ kiện', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (211, 3, N'Máy trộn thực phẩm', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (212, 3, N'Máy rửa bát đĩa', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (213, 3, N'Lò sưởi, Bếp từ & Bộ điều chỉnh gas', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (214, 3, N'Nồi chiên không dầu', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (215, 3, N'Nồi chiên ngập dầu', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (216, 3, N'Lò vi sóng', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (217, 3, N'Lò nướng', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (218, 3, N'Máy nướng bánh', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (219, 3, N'Máy chế biến thực phẩm & Xay thịt', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (220, 3, N'Nồi nấu đa năng', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (221, 3, N'Nồi áp suất', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (222, 3, N'Nồi nấu chậm & Dụng cụ nấu chân không', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (223, 3, N'Nồi cơm điện', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (224, 3, N'Dụng cụ nấu đặc biệt', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (225, 3, N'Tủ lạnh', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (226, 3, N'Tủ đông', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (227, 3, N'Máy hút khói', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (228, 3, N'Khác', 60, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (229, 3, N'Thiết bị an toàn điện tử', 61, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (230, 3, N'Chuông cửa', 61, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (231, 3, N'Công tắc', 61, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (232, 3, N'Thiết bị báo động nhà ở', 61, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (233, 3, N'Thiết bị chống sấm sét', 61, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (234, 3, N'Khác', 61, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (235, 3, N'Đồng hồ thông minh & Vòng đeo tay sức khỏe', 68, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (236, 3, N'Thiết bị thực tế ảo', 68, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (237, 3, N'Thiết bị định vị GPS', 68, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (238, 3, N'Khác', 68, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (239, 3, N'Phụ kiện selfie', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (240, 3, N'Ống kính điện thoại', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (241, 3, N'Đèn flash điện thoại & Đèn selfie', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (242, 3, N'Quạt USB & Quạt điện thoại', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (243, 3, N'Bút cảm ứng', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (244, 3, N'Kẹp điện thoại', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (245, 3, N'Dây đeo điện thoại & Móc khóa', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (246, 3, N'Thẻ nhớ', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (247, 3, N'Thiết bị trình chiếu', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (248, 3, N'Túi đựng điện thoại', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (249, 3, N'Cáp, sạc & bộ chuyển đổi', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (250, 3, N'Đèn USB & Đèn điện thoại', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (251, 3, N'Bộ phát Wifi bỏ túi', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (252, 3, N'Sạc dự phòng & Pin', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (253, 3, N'Phụ kiện cho đồng hồ thông minh', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (254, 3, N'Miếng dán màn hình', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (255, 3, N'Vỏ bao, Ốp lưng & Miếng dán', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (256, 3, N'Khác', 69, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (257, 3, N'Giày bale', 74, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (258, 3, N'Giày lười', 74, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (259, 3, N'Giày Oxford & Giày buộc dây', 74, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (260, 3, N'Giày sục & Giày búp bê', 74, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (261, 3, N'Khác', 74, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (262, 3, N'Xăng-đan đế bằng', 77, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (263, 3, N'Dép kẹp/ dép xỏ ngón', 77, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (264, 3, N'Dép mát-xa', 77, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (265, 3, N'Dép đi trong nhà', 77, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (266, 3, N'Khác', 77, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (267, 3, N'Đồ khử mùi giày', 78, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (268, 3, N'Miếng lót giày', 78, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (269, 3, N'Cây đón gót & Giữ form giày', 78, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (270, 3, N'Đồ chăm sóc và làm sạch giày', 78, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (271, 3, N'Dây giày', 78, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (272, 3, N'Khác', 78, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (273, 3, N'Dây đồng hồ', 83, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (274, 3, N'Dụng cụ sửa chữa', 83, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (275, 3, N'Khóa đồng hồ', 83, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (276, 3, N'Pin đồng hồ', 83, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (277, 3, N'Hộp đựng đồng hồ', 83, NULL)
INSERT [dbo].[category] ([id], [level], [name], [parent_id], [poster_url]) VALUES (278, 3, N'Khác', 83, NULL)
SET IDENTITY_INSERT [dbo].[category] OFF
GO
