version: "3"

services:
    spring-app:
        image: be-bee-ec:0.0.1
        container_name: springboot-app
        ports:
            - "8080:8080"
        depends_on:
            - logstash
            - elasticsearch
            - kibana
            - mssql
            - redis
        networks:
            - elastic
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql_springboot
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Fpoly@123"
            ACCEPT_EULA: "Y"
        networks:
            - elastic
    redis:
        image: redis:latest
        container_name: redis_springboot
        ports:
            - "6379:6379"
        networks:
            - elastic
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        container_name: elasticsearch_springboot
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.type=single-node"
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:8.10.2
        container_name: kibana_springboot
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        depends_on:
            - elasticsearch
        networks:
            - elastic

    logstash:
        image: docker.elastic.co/logstash/logstash:8.10.2
        container_name: logstash_springboot
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
            - ./logstash/libs/mssql-jdbc-8.2.2.jre11.jar:/usr/share/logstash/logstash-core/lib/jars/mssql-jdbc-8.2.2.jre11.jar:ro
        ports:
            - "5044:5044"
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elastic
        depends_on:
            - elasticsearch
networks:
    elastic:
        driver: bridge
volumes:
    elasticsearch_data:
        driver: local